### PR TITLE
fix: resolve xo from cwd if possible

### LINKED ISSUE #19: Cannot find module 'eslint-plugin-react'
Hi, After last update I got following error when trying to lint.

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: 
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.load (/Users/AronHafner/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
```

Have solved it with install `eslint-plugin-react` in the _packages/linter-xo/node_modules/xo_ path. But don't think thats a solution for the long term.

### LINKED ISSUE #41: Use the local XO when available
Like the CLI does. Should have done this from the start. Can't remember why I didn't.

### PR DESCRIPTION
**Pull request by marionebl**
* follow-up for #46
* builds on #47
* closes #19
* closes #41

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks good. Can you fix the merge conflict?

**Comment by marionebl** [comment]
Done!

**Comment by sindresorhus** [comment]
Thanks 🤘

**Comment by marionebl** [comment]
🚀

**Pull request merged**
